### ISSUE TITLE
[OpenAPI] Add securitySchemes

### ISSUE THREAD

**Issue by lcawl** [elastic/elasticsearch-specification#3197]
priority: low
effort: low

## 🚀 Feature Proposal

The OpenAPI documents are missing [securitySchemes](https://spec.openapis.org/oas/v3.0.3#security-scheme-object) and [security](https://spec.openapis.org/oas/v3.0.3#openapi-object) declarations.

They could perhaps be added similarly to the `info` in https://github.com/elastic/elasticsearch-specification/blob/main/compiler/src/steps/add-info.ts

NOTE: I believe that you could have the same list of securitySchemes for both documents, but the `security` list for the serverless document would not include `basicAuth`.

## Motivation

Relates to https://github.com/elastic/docs-content/issues/192

## Example

In the [Kibana](https://github.com/elastic/kibana/blob/main/oas_docs/output/kibana.yaml) openAPI document, it looks like this:

```
security:
  - apiKeyAuth: []
  - basicAuth: []

...

  securitySchemes:
    apiKeyAuth:
      description: |
        These APIs use key-based authentication. You must create an API key and use the encoded value in the request header. For example: `Authorization: ApiKey base64AccessApiKey`
      in: header
      name: Authorization
      type: apiKey
    basicAuth:
      scheme: basic
      type: http
```

As a stop gap, we're implementing them via overlays: https://github.com/elastic/elasticsearch-specification/blob/7a7e2a257032dcadda0f1aeec9344598a2e12913/docs/overlays/elasticsearch-serverless-openapi-overlays.yaml#L22 and https://github.com/elastic/elasticsearch-specification/blob/7a7e2a257032dcadda0f1aeec9344598a2e12913/docs/overlays/elasticsearch-openapi-overlays.yaml#L27
